/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    services: Service;
    projects: Project;
    partners: Partner;
    faq: Faq;
    team: Team;
    'devis-requests': DevisRequest;
    'devis-forms': DevisForm;
    'quote-documents': QuoteDocument;
    media: Media;
    sites: Site;
    redirects: Redirect;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    'devis-requests': DevisRequestsSelect<false> | DevisRequestsSelect<true>;
    'devis-forms': DevisFormsSelect<false> | DevisFormsSelect<true>;
    'quote-documents': QuoteDocumentsSelect<false> | QuoteDocumentsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    sites: SitesSelect<false> | SitesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('fr' | 'ar' | 'en') | ('fr' | 'ar' | 'en')[];
  globals: {
    group: Group;
  };
  globalsSelect: {
    group: GroupSelect<false> | GroupSelect<true>;
  };
  locale: 'fr' | 'ar' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL segment shared by all 3 languages, e.g. pompage-solaire. Generated from the title if empty.
   */
  slug: string;
  /**
   * The website that publishes this content.
   */
  site: number | Site;
  layout?:
    | (
        | HeroBlock
        | StatsBlock
        | ActivityGridBlock
        | FeaturesBlock
        | ProjectsBlock
        | CtaBlock
        | RichTextBlock
        | LogosBlock
        | PartnersBlock
        | FaqBlock
      )[]
    | null;
  /**
   * Optional — overrides the title and description used by search engines.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites".
 */
export interface Site {
  id: number;
  /**
   * Technical id of the site (don't change it once live).
   */
  key: 'growing' | 'hikview' | 'group';
  /**
   * Shown for an unknown domain (and locally on localhost).
   */
  isDefault?: boolean | null;
  /**
   * E.g. https://growing-technologies.tn — used for canonical links, sharing and SEO. Empty = NEXT_PUBLIC_SITE_URL.
   */
  url?: string | null;
  /**
   * Domains that show this site (www. is matched automatically). Locally: <site>.localhost:3000.
   */
  domains?:
    | {
        domain: string;
        id?: string | null;
      }[]
    | null;
  companyName: string;
  legalName: string;
  /**
   * Format : 1234567/A/B/M/000
   */
  matriculeFiscal: string;
  certification?: string | null;
  /**
   * Subtitle of /services, e.g. “Four activities, from solar pumping to PV plants.”
   */
  servicesIntro?: string | null;
  /**
   * One sentence: browser tab title, search engines, home visual.
   */
  tagline: string;
  /**
   * PNG/WebP, transparent background. Empty = badge with the initials below.
   */
  logo?: (number | null) | Media;
  /**
   * Optional.
   */
  logoDark?: (number | null) | Media;
  /**
   * Checked: the company name isn't written next to the logo.
   */
  logoIncludesName?: boolean | null;
  /**
   * E.g. GT — used when no logo is uploaded.
   */
  monogram?: string | null;
  /**
   * Square PNG, 512×512 recommended.
   */
  favicon?: (number | null) | Media;
  /**
   * Hex code (#1f6fd1). Hue and intensity are used; lightness is adjusted automatically to keep text readable. Empty = default palette (solar green / gold).
   */
  theme?: {
    primary?: string | null;
    accent?: string | null;
  };
  email: string;
  phone: string;
  whatsapp?: string | null;
  /**
   * @username
   */
  telegram?: string | null;
  address: string;
  city: string;
  hours?: string | null;
  coords: {
    lat: number;
    lng: number;
  };
  /**
   * Header menu. The “Request a quote” button is added automatically.
   */
  navItems?:
    | {
        label: string;
        /**
         * Path without locale, e.g. /services — the locale is added automatically.
         */
        href: string;
        comingSoon?: boolean | null;
        id?: string | null;
      }[]
    | null;
  footer?: {
    tagline?: string | null;
    quickLinks?:
      | {
          label: string;
          /**
           * Path without locale, e.g. /services — the locale is added automatically.
           */
          href: string;
          id?: string | null;
        }[]
      | null;
    legalLinks?:
      | {
          label: string;
          /**
           * Path without locale, e.g. /services — the locale is added automatically.
           */
          href: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Each new request on this site is sent to these addresses and this Telegram group. Empty = the site's email (and, for the default site, DEVIS_NOTIFY_EMAIL / TELEGRAM_CHAT_ID).
   */
  notify?: {
    emails?:
      | {
          email: string;
          id?: string | null;
        }[]
      | null;
    /**
     * E.g. -5544656539 (the TELEGRAM_BOT_TOKEN bot must be a member of the group).
     */
    telegramChatId?: string | null;
  };
  socials?: {
    facebook?: string | null;
    instagram?: string | null;
    linkedin?: string | null;
  };
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describes the image for screen readers and SEO (translate in each language).
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  style: 'full' | 'compact';
  badge?: string | null;
  title: string;
  subtitle?: string | null;
  primaryCta?: {
    label?: string | null;
    /**
     * Path without locale, e.g. /services — the locale is added automatically.
     */
    href?: string | null;
  };
  secondaryCta?: {
    label?: string | null;
    /**
     * Path without locale, e.g. /services — the locale is added automatically.
     */
    href?: string | null;
  };
  image?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock".
 */
export interface StatsBlock {
  title?: string | null;
  useSiteStats?: boolean | null;
  items?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ActivityGridBlock".
 */
export interface ActivityGridBlock {
  title?: string | null;
  subtitle?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'activityGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturesBlock".
 */
export interface FeaturesBlock {
  title?: string | null;
  subtitle?: string | null;
  items?:
    | {
        icon?:
          | (
              | 'PlugZap'
              | 'Droplets'
              | 'BatteryCharging'
              | 'Cable'
              | 'Zap'
              | 'Sun'
              | 'House'
              | 'Building2'
              | 'Factory'
              | 'Tractor'
              | 'Lightbulb'
              | 'RadioTower'
              | 'Cctv'
              | 'Siren'
              | 'Fingerprint'
              | 'Flame'
              | 'Network'
              | 'Router'
              | 'Wifi'
              | 'Server'
              | 'Phone'
              | 'ScanBarcode'
              | 'Store'
              | 'Monitor'
              | 'Presentation'
              | 'Tv'
              | 'ListOrdered'
              | 'Video'
              | 'Cpu'
              | 'Landmark'
              | 'ShieldCheck'
              | 'MapPin'
              | 'Wrench'
              | 'Headphones'
              | 'Award'
              | 'Heart'
              | 'Eye'
            )
          | null;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'features';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProjectsBlock".
 */
export interface ProjectsBlock {
  title?: string | null;
  subtitle?: string | null;
  /**
   * Shows “featured” projects, most recent first.
   */
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'projects';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock".
 */
export interface CtaBlock {
  title: string;
  subtitle?: string | null;
  button?: {
    label?: string | null;
    /**
     * Path without locale, e.g. /services — the locale is added automatically.
     */
    href?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  title?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogosBlock".
 */
export interface LogosBlock {
  title?: string | null;
  logos?:
    | {
        image: number | Media;
        name: string;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'logos';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnersBlock".
 */
export interface PartnersBlock {
  title?: string | null;
  /**
   * Empty = all. Logos are managed in Content → Partners & brands.
   */
  kinds?: ('manufacturer' | 'distributor' | 'own-product' | 'certification')[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'partners';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock".
 */
export interface FaqBlock {
  title?: string | null;
  /**
   * Empty = all questions.
   */
  items?: (number | Faq)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  /**
   * The website that publishes this content.
   */
  site: number | Site;
  question: string;
  answer: string;
  /**
   * Same label = same group, e.g. “Subsidies”.
   */
  category: string;
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * URL segment shared by all 3 languages, e.g. pompage-solaire. Generated from the title if empty.
   */
  slug: string;
  /**
   * The website that publishes this content.
   */
  site: number | Site;
  /**
   * Empty = main service (/services/…). Otherwise a sub-service of this area (/services/area/…).
   */
  parent?: (number | null) | Service;
  /**
   * The service appears in the quote form with these questions. Empty = the quote button leads to the Contact page.
   */
  devisForm?: (number | null) | DevisForm;
  /**
   * Lists every “Public / B2G” project of the site on this page (e.g. the B2G integrator page).
   */
  showPublicReferences?: boolean | null;
  /**
   * Links the service to the quote form. Empty = the quote button leads to the Contact page.
   */
  activityKey?: ('raccorde' | 'pompage' | 'isole' | 'bt' | 'mt') | null;
  icon:
    | 'PlugZap'
    | 'Droplets'
    | 'BatteryCharging'
    | 'Cable'
    | 'Zap'
    | 'Sun'
    | 'House'
    | 'Building2'
    | 'Factory'
    | 'Tractor'
    | 'Lightbulb'
    | 'RadioTower'
    | 'Cctv'
    | 'Siren'
    | 'Fingerprint'
    | 'Flame'
    | 'Network'
    | 'Router'
    | 'Wifi'
    | 'Server'
    | 'Phone'
    | 'ScanBarcode'
    | 'Store'
    | 'Monitor'
    | 'Presentation'
    | 'Tv'
    | 'ListOrdered'
    | 'Video'
    | 'Cpu'
    | 'Landmark';
  order: number;
  /**
   * Shown on cards (≈ 1 sentence).
   */
  shortDescription: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Parts of the page with their own anchor, e.g. #commercial → /fr/services/installation-raccordee#commercial.
   */
  sections?:
    | {
        anchor: string;
        icon?:
          | (
              | 'PlugZap'
              | 'Droplets'
              | 'BatteryCharging'
              | 'Cable'
              | 'Zap'
              | 'Sun'
              | 'House'
              | 'Building2'
              | 'Factory'
              | 'Tractor'
              | 'Lightbulb'
              | 'RadioTower'
              | 'Cctv'
              | 'Siren'
              | 'Fingerprint'
              | 'Flame'
              | 'Network'
              | 'Router'
              | 'Wifi'
              | 'Server'
              | 'Phone'
              | 'ScanBarcode'
              | 'Store'
              | 'Monitor'
              | 'Presentation'
              | 'Tv'
              | 'ListOrdered'
              | 'Video'
              | 'Cpu'
              | 'Landmark'
            )
          | null;
        title: string;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  heroImage?: (number | null) | Media;
  benefits?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  process?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Complementary services of another group company, suggested at the bottom of this page (e.g. video surveillance for a solar plant).
   */
  crossSell?: (number | Service)[] | null;
  faqRefs?: (number | Faq)[] | null;
  /**
   * Optional — overrides the title and description used by search engines.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * The technical questions asked for a service. Link a form to a service in Services → Quote form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "devis-forms".
 */
export interface DevisForm {
  id: number;
  title: string;
  /**
   * The website that publishes this content.
   */
  site: number | Site;
  /**
   * In display order. Contact details (name, phone, governorate…) and consent are added automatically.
   */
  questions?:
    | {
        label: string;
        type: 'text' | 'textarea' | 'number' | 'select' | 'radio' | 'multiselect' | 'checkbox' | 'date';
        /**
         * Technical id, e.g. flowM3PerDay. Don't change it once used.
         */
        name: string;
        help?: string | null;
        required?: boolean | null;
        width?: ('half' | 'full') | null;
        /**
         * Same word on several questions = at least one of them must be filled (e.g. “usage” for bill OR consumption).
         */
        requiredGroup?: string | null;
        unit?: string | null;
        min?: number | null;
        max?: number | null;
        options?:
          | {
              label: string;
              value: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Optional: the key of an earlier question and the expected value (e.g. subtype = eclairage-public).
         */
        showIf?: {
          field?: string | null;
          equals?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * URL segment shared by all 3 languages, e.g. pompage-solaire. Generated from the title if empty.
   */
  slug: string;
  /**
   * The website that publishes this content.
   */
  site: number | Site;
  activity: number | Service;
  clientType: 'residentiel' | 'agricole' | 'industriel' | 'public';
  /**
   * E.g. “Sbeitla municipality”. Leave empty for an anonymous client.
   */
  client?: string | null;
  clientNamePublic?: boolean | null;
  region: string;
  /**
   * Empty for LV/MV.
   */
  powerKwc?: number | null;
  date: string;
  summary: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  coverImage?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  featured?: boolean | null;
  /**
   * Optional — overrides the title and description used by search engines.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  kind: 'manufacturer' | 'distributor' | 'own-product' | 'certification';
  logo: number | Media;
  url?: string | null;
  /**
   * Optional — one sentence, mainly for the group's own products.
   */
  description?: string | null;
  sites: (number | Site)[];
  /**
   * The logo is also shown on these service pages.
   */
  services?: (number | Service)[] | null;
  showInStrip?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  /**
   * The website that publishes this content.
   */
  site: number | Site;
  name: string;
  role: string;
  photo?: (number | null) | Media;
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "devis-requests".
 */
export interface DevisRequest {
  id: number;
  reference?: string | null;
  /**
   * The client (if they gave an email) is notified at “Quote sent” and “Won”.
   */
  status: 'nouveau' | 'contacte' | 'devis-envoye' | 'gagne' | 'perdu';
  /**
   * Required for “Quote sent”: it is attached to the client's email. If the client gave no email, send it on WhatsApp.
   */
  quote?: (number | null) | QuoteDocument;
  locale?: ('fr' | 'ar' | 'en') | null;
  /**
   * Never shown to the client.
   */
  notes?: string | null;
  /**
   * Filled automatically; the dates appear on the client's tracking page.
   */
  statusHistory?:
    | {
        status: 'nouveau' | 'contacte' | 'devis-envoye' | 'gagne' | 'perdu';
        changedAt: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The website that publishes this content.
   */
  site: number | Site;
  service?: (number | null) | Service;
  activity?: ('raccorde' | 'pompage' | 'isole' | 'bt' | 'mt') | null;
  technicalDetails?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  formSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  raccorde?: {
    monthlyBillTnd?: number | null;
    monthlyConsumptionKwh?: number | null;
    roofType?: ('terrasse' | 'tuiles' | 'bac-acier' | 'sol') | null;
    roofSurfaceM2?: number | null;
    phase?: ('mono' | 'tri') | null;
    propertyType?: ('residentiel' | 'commercial' | 'industriel' | 'agricole') | null;
  };
  pompage?: {
    waterSource?: ('puits' | 'forage' | 'surface') | null;
    depthM?: number | null;
    flowM3PerDay?: number | null;
    headM?: number | null;
    existingPumpCv?: number | null;
  };
  isole?: {
    dailyConsumptionKwh?: number | null;
    autonomyDays?: number | null;
    hasGenset?: boolean | null;
    criticalLoads?: string | null;
  };
  electrical?: {
    workNature?: string | null;
    siteType?: ('residentiel' | 'tertiaire' | 'industriel' | 'agricole' | 'public') | null;
    indicativePowerKva?: number | null;
    existingInstallationNotes?: string | null;
  };
  fullName: string;
  phone: string;
  email?: string | null;
  region:
    | 'ariana'
    | 'beja'
    | 'ben-arous'
    | 'bizerte'
    | 'gabes'
    | 'gafsa'
    | 'jendouba'
    | 'kairouan'
    | 'kasserine'
    | 'kebili'
    | 'kef'
    | 'mahdia'
    | 'manouba'
    | 'medenine'
    | 'monastir'
    | 'nabeul'
    | 'sfax'
    | 'sidi-bouzid'
    | 'siliana'
    | 'sousse'
    | 'tataouine'
    | 'tozeur'
    | 'tunis'
    | 'zaghouan';
  preferredChannel?: ('call' | 'whatsapp' | 'telegram') | null;
  address?: string | null;
  consent: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * Quotes sent to clients. Visible to the team only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quote-documents".
 */
export interface QuoteDocument {
  id: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Without the language: /services/basse-tension redirects /fr/…, /ar/… and /en/….
   */
  from: string;
  /**
   * Path without the language (a #… anchor is allowed) or an external https:// address.
   */
  to: string;
  /**
   * Empty = every site.
   */
  sites?: (number | Site)[] | null;
  /**
   * Search engines transfer the ranking to the new address.
   */
  permanent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor';
  /**
   * Sites whose content and requests this editor manages. Empty = all sites. No effect for an administrator.
   */
  sites?: (number | Site)[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'devis-requests';
        value: number | DevisRequest;
      } | null)
    | ({
        relationTo: 'devis-forms';
        value: number | DevisForm;
      } | null)
    | ({
        relationTo: 'quote-documents';
        value: number | QuoteDocument;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'sites';
        value: number | Site;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  site?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        activityGrid?: T | ActivityGridBlockSelect<T>;
        features?: T | FeaturesBlockSelect<T>;
        projects?: T | ProjectsBlockSelect<T>;
        cta?: T | CtaBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        logos?: T | LogosBlockSelect<T>;
        partners?: T | PartnersBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  style?: T;
  badge?: T;
  title?: T;
  subtitle?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  image?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock_select".
 */
export interface StatsBlockSelect<T extends boolean = true> {
  title?: T;
  useSiteStats?: T;
  items?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ActivityGridBlock_select".
 */
export interface ActivityGridBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturesBlock_select".
 */
export interface FeaturesBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  items?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProjectsBlock_select".
 */
export interface ProjectsBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock_select".
 */
export interface CtaBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  button?:
    | T
    | {
        label?: T;
        href?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogosBlock_select".
 */
export interface LogosBlockSelect<T extends boolean = true> {
  title?: T;
  logos?:
    | T
    | {
        image?: T;
        name?: T;
        url?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnersBlock_select".
 */
export interface PartnersBlockSelect<T extends boolean = true> {
  title?: T;
  kinds?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock_select".
 */
export interface FaqBlockSelect<T extends boolean = true> {
  title?: T;
  items?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  site?: T;
  parent?: T;
  devisForm?: T;
  showPublicReferences?: T;
  activityKey?: T;
  icon?: T;
  order?: T;
  shortDescription?: T;
  body?: T;
  sections?:
    | T
    | {
        anchor?: T;
        icon?: T;
        title?: T;
        body?: T;
        image?: T;
        id?: T;
      };
  heroImage?: T;
  benefits?:
    | T
    | {
        text?: T;
        id?: T;
      };
  process?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  crossSell?: T;
  faqRefs?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  site?: T;
  activity?: T;
  clientType?: T;
  client?: T;
  clientNamePublic?: T;
  region?: T;
  powerKwc?: T;
  date?: T;
  summary?: T;
  body?: T;
  coverImage?: T;
  gallery?: T;
  featured?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  kind?: T;
  logo?: T;
  url?: T;
  description?: T;
  sites?: T;
  services?: T;
  showInStrip?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  site?: T;
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  site?: T;
  name?: T;
  role?: T;
  photo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "devis-requests_select".
 */
export interface DevisRequestsSelect<T extends boolean = true> {
  reference?: T;
  status?: T;
  quote?: T;
  locale?: T;
  notes?: T;
  statusHistory?:
    | T
    | {
        status?: T;
        changedAt?: T;
        id?: T;
      };
  site?: T;
  service?: T;
  activity?: T;
  technicalDetails?: T;
  formSnapshot?: T;
  raccorde?:
    | T
    | {
        monthlyBillTnd?: T;
        monthlyConsumptionKwh?: T;
        roofType?: T;
        roofSurfaceM2?: T;
        phase?: T;
        propertyType?: T;
      };
  pompage?:
    | T
    | {
        waterSource?: T;
        depthM?: T;
        flowM3PerDay?: T;
        headM?: T;
        existingPumpCv?: T;
      };
  isole?:
    | T
    | {
        dailyConsumptionKwh?: T;
        autonomyDays?: T;
        hasGenset?: T;
        criticalLoads?: T;
      };
  electrical?:
    | T
    | {
        workNature?: T;
        siteType?: T;
        indicativePowerKva?: T;
        existingInstallationNotes?: T;
      };
  fullName?: T;
  phone?: T;
  email?: T;
  region?: T;
  preferredChannel?: T;
  address?: T;
  consent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "devis-forms_select".
 */
export interface DevisFormsSelect<T extends boolean = true> {
  title?: T;
  site?: T;
  questions?:
    | T
    | {
        label?: T;
        type?: T;
        name?: T;
        help?: T;
        required?: T;
        width?: T;
        requiredGroup?: T;
        unit?: T;
        min?: T;
        max?: T;
        options?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        showIf?:
          | T
          | {
              field?: T;
              equals?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quote-documents_select".
 */
export interface QuoteDocumentsSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites_select".
 */
export interface SitesSelect<T extends boolean = true> {
  key?: T;
  isDefault?: T;
  url?: T;
  domains?:
    | T
    | {
        domain?: T;
        id?: T;
      };
  companyName?: T;
  legalName?: T;
  matriculeFiscal?: T;
  certification?: T;
  servicesIntro?: T;
  tagline?: T;
  logo?: T;
  logoDark?: T;
  logoIncludesName?: T;
  monogram?: T;
  favicon?: T;
  theme?:
    | T
    | {
        primary?: T;
        accent?: T;
      };
  email?: T;
  phone?: T;
  whatsapp?: T;
  telegram?: T;
  address?: T;
  city?: T;
  hours?: T;
  coords?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  navItems?:
    | T
    | {
        label?: T;
        href?: T;
        comingSoon?: T;
        id?: T;
      };
  footer?:
    | T
    | {
        tagline?: T;
        quickLinks?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        legalLinks?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
      };
  notify?:
    | T
    | {
        emails?:
          | T
          | {
              email?: T;
              id?: T;
            };
        telegramChatId?: T;
      };
  socials?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        linkedin?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  sites?: T;
  permanent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  sites?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "group".
 */
export interface Group {
  id: number;
  name: string;
  /**
   * Subtitle of the “Our group” page.
   */
  tagline?: string | null;
  story?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Order and presentation of the companies (logo, name and address come from Sites).
   */
  members?:
    | {
        site: number | Site;
        summary?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Shows “Member of … group” and the other companies at the bottom of every page.
   */
  footerBand?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "group_select".
 */
export interface GroupSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  story?: T;
  members?:
    | T
    | {
        site?: T;
        summary?: T;
        id?: T;
      };
  footerBand?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}