import {
  Award,
  BatteryCharging,
  Briefcase,
  Building2,
  Cable,
  Cctv,
  Cpu,
  Droplets,
  Eye,
  Factory,
  Fingerprint,
  Flame,
  Headphones,
  Heart,
  House,
  Landmark,
  Lightbulb,
  ListOrdered,
  MapPin,
  Monitor,
  Network,
  Newspaper,
  Phone,
  PlugZap,
  Presentation,
  RadioTower,
  Router,
  ScanBarcode,
  Server,
  ShieldCheck,
  Siren,
  Store,
  Sun,
  Tractor,
  Tv,
  UserRound,
  Video,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
  type LucideProps,
} from "lucide-react";
import { isIconName, type IconName } from "@/lib/icons";

/** Must cover every name the CMS offers (see src/lib/icons.ts). */
const iconMap: Record<IconName, LucideIcon> = {
  PlugZap,
  Droplets,
  BatteryCharging,
  Cable,
  Zap,
  Sun,
  ShieldCheck,
  MapPin,
  Wrench,
  Headphones,
  Award,
  Heart,
  Eye,
  UserRound,
  Briefcase,
  Newspaper,
  House,
  Building2,
  Factory,
  Tractor,
  Lightbulb,
  RadioTower,
  Cctv,
  Siren,
  Fingerprint,
  Flame,
  Network,
  Router,
  Wifi,
  Server,
  Phone,
  ScanBarcode,
  Store,
  Monitor,
  Presentation,
  Tv,
  ListOrdered,
  Video,
  Cpu,
  Landmark,
};

/** Renders a CMS-selected icon by name; unknown names fall back to the sun. */
export function DynamicIcon({
  name,
  ...props
}: { name: string | null | undefined } & Omit<LucideProps, "name">) {
  const Icon = isIconName(name) ? iconMap[name] : Sun;
  return <Icon aria-hidden {...props} />;
}
